services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airbnbark
    volumes:
      - pgdata:/var/lib/postgresql/data
      # init.sql removed - Prisma handles schema and seeding
    ports:
      - "5433:5432"

  api:
    build: ./apps/api
    restart: unless-stopped
    environment:
      PORT: 3000
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: airbnbark
      DATABASE_URL: postgresql://postgres:postgres@db:5432/airbnbark
      JWT_SECRET: airbonbark-dev-secret-key-2026-x7k9m2p4q8r1s5t3
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  web:
    build: ./apps/web
    restart: unless-stopped
    ports:
      - "5173:5173"

  # woobot:
  #   build: ./apps/woobot
  #   restart: unless-stopped
  #   environment:
  #     PORT: 4000
  #   ports:
  #     - "4000:4000"

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro,z
    depends_on:
      - api
      - web

  redis:
    image: redis:8.4.0-alpine
    restart: unless-stopped
    # No host port mapping so Redis is only reachable from other containers
    # no data persistance
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db

volumes:
  pgdata:
